# Generated by Django 4.1.6 on 2023-02-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_options_remove_account_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_created',
            new_name='date_joined',
        ),
    ]
