# Generated by Django 4.1.6 on 2023-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_options_transaction_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], default='Confirmed', max_length=100, null=True),
        ),
    ]
