# Generated by Django 4.1.6 on 2023-03-03 09:51

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_wallet_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='package name', max_length=200)),
                ('capital', models.IntegerField()),
                ('roi', models.DecimalField(decimal_places=2, help_text='Return on Investment Percentage', max_digits=20000)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='crypto_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='depositor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='fiat_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default=core.models.random_char, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentpackages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
