# Generated by Django 4.1.6 on 2023-03-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_investmentpackages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentPackages',
            new_name='InvestmentPackage',
        ),
    ]
